pwksgem:
  name: PromptWorks Gem
  service: test
  access_key: fa145f4dd72c390f8d83b41bbdd39ee6
  secret_key: 603c3baff7cb4fe4876b5b5965cfee16a4282ac3818a4aea84c687a56955262a07ef9fbac0d149b8a964270c76e2ffd1668b1106ee9349ec8557e00be898a8022559a45d10d64c7d94fa32e97cd713160ea6e028c33c4cde9966f39b5614b23bc9271c94a0814d0dbadc72ccb3d002fe08e8ba962e1d4d3494302f56d2eb1123
  success_url: /responses
  transaction_type: sale,create_payment_token
  endpoint_type: standard
  payment_method: card
  locale: en-us
  currency: USD
  unsigned_field_names:
    - bill_to_email
    - bill_to_forename
    - bill_to_surname
    - bill_to_address_line1
    - bill_to_address_line2
    - bill_to_address_country
    - bill_to_address_state
    - bill_to_address_postal_code
    - bill_to_address_city
    - card_cvn
    - card_expiry_date
    - card_number
    - card_type
