development:
  adapter: postgresql
  database: cybersourcery_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cybersourcery_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cybersourcery_prod
  pool: 5
  timeout: 5000
